In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 37.4 MB/s  0:00:006m0:00:01
Downloading numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 47.2 MB/s  0:00:006m0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.0 pandas-3.0.3

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip

In [4]:
import pandas as pd

In [8]:
data= [['Juan',25],['Pedro',34],['Luis',45]]
df= pd.DataFrame (data, columns= ['Nombre','Edad'])

In [9]:
df

  Nombre  Edad
0   Juan    25
1  Pedro    34
2   Luis    45

In [5]:
#Crear Data Frame a partir de un diccionario 
data={
    'Nombre': ['Juan','Pedro', 'Luis'],
    'Edad': [25,26,30]
}

df= pd.DataFrame(data)

In [6]:
df

  Nombre  Edad
0   Juan    25
1  Pedro    26
2   Luis    30

In [7]:
##Ler un archivo de una ruta indicada
df= pd.read_csv('utils/data/data.csv')
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [9]:
## leer un archivo sin extension y con  un separador especial 
df=pd.read_csv('utils/data/data', sep = '|')
df

  nombre  edad     ciudad
0   Juan   NaN     Madrid
1  María  30.0  Barcelona
2  Pedro  35.0    Sevilla

In [11]:
#leer un archivo csv sin cabecera
df=pd.read_csv('utils/data/data_without_header',
               sep=',',
               header=None,
               names=['Nombre','Edad','Ciudad']
               )

df

  Nombre  Edad     Ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla